### ISSUE TITLE
`SetBuilder.where` and `SetBuilder.retainWhere` are redundant

### ISSUE THREAD

**Issue by pschiffmann** [google/built_collection.dart#105]
And `.where` allocates a new `Set`, whereas `.retainWhere` works in-place. :)

**Comment by davidmorgan** [comment]
Good point. Bit of a clash between the goals of adapting the Set interface and copying the Iterable interface.

The "where" implementation could be changed to call "retainWhere". I'm not sure it's worth dropping one of them. What do you think?

**Comment by pschiffmann** [comment]
> I'm not sure it's worth dropping one of them.
Agreed. Dropping either one would break consistency with with the design decision to implement the respective interface.

You could document that both methods are interchangeable to avoid confusion, though.

**Comment by davidmorgan** [comment]
Sounds good to me. Thanks.

**Comment by davidmorgan** [comment]
Fixed in https://github.com/google/built_collection.dart/pull/112
