### ISSUE TITLE
Bump quiver dependency

### ISSUE THREAD

**Issue by sroddy** [google/built_collection.dart#108]
Hi,
can you please increase the dependencies of this lib to support `quiver 0.26.0`, in order to be able to use this package in the latest master of Flutter?

 Thanks a lot

**Comment by davidmorgan** [comment]
Done. Thanks!

**Comment by mogol** [comment]
Hi,
I have the same issue with new flutter version 
```
Running "flutter packages upgrade" in ***...
Incompatible version constraints on quiver:
- built_collection 3.0.2 depends on version >=0.21.0 <0.28.0
- flutter_test 0.0.0 depends on version 0.28.0
```
