### ISSUE TITLE
release 2.1.1 is a breaking change for classes that implement a built collection type

### ISSUE THREAD

**Issue by pschiffmann** [google/built_collection.dart#124]

**Comment by dave26199** [comment]
You're right, I should have bumped the major version number. Sorry about that.

It will be a couple of weeks before I can address this, unfortunately, as I'm on vacation. Then I'll release another 2.1 release that reverts it and re-release as 3.0.

**Comment by davidmorgan** [comment]
Done. Please let me know if you see any further issues. Thanks!
