### ISSUE TITLE
DDC giving numerous cast errors

### ISSUE THREAD

**Issue by jimmyff** [google/built_collection.dart#132]
Since moving to DDC I've been getting a having a lot of cast exceptions. Yesterday I rewrote a chunk of code to avoid this error:
```
CastError: Casting value of type '_Future<BaseModel>' to type 'Future<SearchPublicProfileSummaryResponse>' which is incompatible
```
I would have expected it to work as SearchPublicProfileSummaryResponse extends BaseModel. I worked around the error by making the queueQuery method generic: `Future<T> queueQuery<T>(..) async { … }` and then using: `app.queueQuery<SearchPublicProfileSummaryResponse>(…)` to query it.

Today I keep seeing these messages crop up in the console:

```
dart_sdk.js:5848 Ignoring cast fail from ImmutableMap to Map<Type, Serializer>
```

```
dart_sdk.js:5848 Ignoring cast fail from ImmutableMap to Map<String, Serializer>
```

```
dart_sdk.js:5848 Ignoring cast fail from ImmutableMap to Map<FullType, Function>
```

```
dart_sdk.js:5848 Ignoring cast fail from JSArray to List<int>
```

```
dart_sdk.js:5848 Ignoring cast fail from _Future to Future<MessagingConversationsResponse>
```

All of these exceptions seem to be with built types failing to cast to regular types?

**Comment by davidmorgan** [comment]
The error with `Future` is because it's trying to cast a `_Future`, which is not a `Future`. It's possible something could be improved in the SDK here, but I don't think it relates to `built_value`.

The messages related to ImmutableMap look like they could be related to `built_value`. Is there by any chance a stack trace associated so I can see where in the `built_value` code they're coming from?

Thanks.

**Comment by davidmorgan** [comment]
Looks like there is an issue with the default map type in MapBuilder:

```
factory MapBuilder([map = const {}]) {
```

-- this is where `ImmutableMap` without a type is coming from. I'll take a look.

**Comment by davidmorgan** [comment]
We also need to handle the case where the user passes in a `<dynamic>{}`.

**Comment by munificent** [comment]
> The error with Future is because it's trying to cast a _Future, which is not a Future. It's possible something could be improved in the SDK here, but I don't think it relates to built_value.

No, the message isn't clear, but it's because of the type argument, not because of the private `_Future` class, which does implement `Future`. It's warning you that a cast from `Future<dynamic>` to `Future<MessagingConversationsResponse>` is being ignored. In Dart 2, that's a runtime error.

**Comment by davidmorgan** [comment]
@munificent that's the case for this error

```
dart_sdk.js:5848 Ignoring cast fail from _Future to Future<MessagingConversationsResponse>
```

--I was talking about the first one, sorry I wasn't clear

```
CastError: Casting value of type '_Future<BaseModel>' to type 'Future<SearchPublicProfileSummaryResponse>' which is incompatible
```

but actually I see I was wrong about that one. Rather the problem is that it's a downcast of the generic which is not allowed.
