### ISSUE TITLE
Fully support Dart 2

### ISSUE THREAD

**Issue by davidmorgan** [google/built_collection.dart#136]
We will likely want to add new methods to make use of what's available in Dart 2.

**Comment by davidmorgan** [comment]
I looked at removing the remaining type checks in `ListBuilder`, `SetBuilder` and `MapBuilder`. These are redundant with Dart 2's own type checks now. The reason to remove them would be performance.

On the VM, it doesn't seem to make much difference. With or without checks we can add about 100 million elements to a list per second.

On the web, with dart2js, and with optimization turned up to maximum, it makes about a x10 difference. Without checks performance is comparable to the VM: 100 million elements per second. With checks, it's more like 10 million.

This would be a clear win for turning off the checks ... except that dart2js with optimizations turned to max does _not_ do the checks required by Dart 2. So in fact this leaves a hole which could allow incorrect types to get into your collections. It's not clear if the performance gain is worth this happening for common built_collection use cases. Perhaps we could make it an option.

**Comment by zoechi** [comment]
Is there no option in dart2js where this can be specified instead? (`-ox`)

**Comment by davidmorgan** [comment]
Yes, dart2js does full Dart 2 checking by default. But this makes `built_collection` _much_ slower. In general I think for production use right now many (most?) will want to turn the checks off. This is done for `-O2` and higher.

**Comment by zoechi** [comment]
But you think people might want different settings for built_value code and other code?
