### ISSUE TITLE
Allow null collection

### ISSUE THREAD

**Issue by kentcb** [google/built_collection.dart#141]
For a nullable list:

```dart
abstract class Foo ... {
  @nullable
  BuiltList<Whatever> get whatevers;

  ...
}
```
Attempting to replace the collection back with `null` fails:
```dart
foo.rebuild((b) => b.whatevers.replace(null));
```
This is because `ListBuilder<T>.replace(Iterable)` does not anticipate that `iterable` might be `null`. Relevant stack:
```
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      new List.from (dart:core-patch/dart:core/array_patch.dart:58)
#2      ListBuilder.replace (package:built_collection/src/list/list_builder.dart:52:24)
```

Whilst I could get around this, it feels really hacky and counter-intuitive:
```dart
var whateversBuilder = myThingThatMightContainNull.whatevers?.toBuilder();
return foo.rebuild((b) => b..whatevers = whateversBuilder);
```

**Comment by davidmorgan** [comment]
Thanks. I agree this is currently non-optimal. I have an issue open at built_value that includes this one, although it doesn't mention it explicitly:

https://github.com/google/built_value.dart/issues/126

The implementation is a little awkward. In particular I would like for `build` to always return a non-null value, so the builder will need a new `buildOrNull` method for when it's allowed to be null. `built_value` can automatically use the correct method, of course.

But, yes, I'd like to do this.

**Comment by davidmorgan** [comment]
(tracking with the `built_value` issue).
