### ISSUE TITLE
Allow custom headers for generated files

### ISSUE THREAD

**Issue by zoechi** [google/built_collection.dart#143]
like https://github.com/dart-lang/json_serializable/blob/master/example/build.yaml

To add `// ignore_for_file: ...` or similar

**Comment by davidmorgan** [comment]
Did you mean to file this for `built_value`?

Looks pretty easy to do, basically this line here:

https://github.com/dart-lang/json_serializable/blob/master/json_serializable/lib/builder.dart#L10

**Comment by zoechi** [comment]
Sorry, yes, I meant `built_value`

**Comment by zoechi** [comment]
`headers` **and** `additionalHeaders` would be nice in case one only wants to add to default headers instead of replacing, but it's your call if you think this is worth it.

**Comment by davidmorgan** [comment]
Sounds good. Thanks!

Filed over here:

https://github.com/google/built_value.dart/issues/374
