### ISSUE TITLE
Add removeWhere to BuiltMap

### ISSUE THREAD

**Issue by charafau** [google/built_collection.dart#146]
Currently it's possible to filter `BuiltList` and create a new one like this:

```dart
var list = new BuiltList<int>([1, 2, 3, 4]);

var list2 = list.where((int val) => val != 2);

// list2 = [1,3,4
```

but issue appears when you want to filter `BuiltMap` in functional style, there's `remove()` method but you can only pass key to it like:

```dart 
  BuiltMap<int, String> myMap = new BuiltMap<int, String>({1: '1', 2: '2'});

  var m = myMap.rebuild((b) => b
  ..remove(1)
  );
//m = {2: '2'}
```

it would be nice to have `removeWhere()` or `where()` which would filter collection by passing filtering function to it.

**Comment by davidmorgan** [comment]
I usually try to keep the `built_collection` APIs as close as possible to the SDK ones; that way they're future-proof.

With that in mind, it's a bit awkward, but you can do what you want like this:

```
var m = myMap.rebuild((b) => myMaps.keys.where((val) => val != 2).forEach(b.remove));
```

and similarly with `myMaps.values`.

**Comment by pschiffmann** [comment]
Dart 2 adds a `removeWhere` method to map: https://api.dartlang.org/dev/2.0.0-dev.58.0/dart-core/Map/removeWhere.html
So this issue will probably be solved with #136.

**Comment by davidmorgan** [comment]
Thanks! I _thought_ there were some relevant `Map` additions in Dart 2, but I was looking in the wrong place when I checked just now.

Yes, we'll add equivalents to all the new Dart 2 methods.

I'm waiting for the various Dart 2 runtimes to be better established (VM, dart2js) before working on the Dart 2 methods, so that I can rely on Dart 2 features.

**Comment by davidmorgan** [comment]
We now have `removeWhere` :)
