### ISSUE TITLE
Deserialize list of multiple types not possible?

### ISSUE THREAD

**Issue by BerndWessels** [google/built_collection.dart#147]
Hi
I have a pretty common use case but can't figure out how to do it with `BuiltList`.

I have a list of `item` and `section` elements in my firestore collection:

item type
```json
{
  "order": 4,
  "title": "item 4",
  "color": "red"
}
```

section type
```json
{
  "order": 17,
  "name:" "section 2"
}
```

so in firestore my collection has many `item`s and many `section`s.

Now if flutter I get this collection like this:

```dart
firestore.collection("menus/il86e4qdVawW6ixia1XU/elements").snapshots().listen((QuerySnapshot snapshot) {
}
```

Now I want a `BuiltList` from that.

So ideally I would have a
`MenuElement` `abstract` `class`
and
`MenuItem` `class` and `MenuSection` `class` that both implement `MenuElement`
and then a `BuiltList<MenuElement>`

But I just can't figure out how to achieve that because
1. The values in the `BuiltList` should be `BuiltValue` and I can't tell them to implement `MenuElement`.
2. I have no idea how to deserialize the `snapshot` which is `JSON` with elements of the 2 different types.

Is this at all possible?

It is a pretty common thing for lists to have sections and items and I hope there is a way to achieve this.

**Comment by dave26199** [comment]
I see you opened this over at built_value.dart--that's the best place for it, so I'll close this one.
