### ISSUE TITLE
Convenience rebuild methods

### ISSUE THREAD

**Issue by davidmarne** [google/built_collection.dart#153]
It would be nice if, for example, BuiltList implemented all of the same mutation methods as ListBuilder but rather than being void methods that mutate the instance, the methods returned a new instance of the BuiltList. Using the rebuild() function is nice when you have to make multiple changes to a list, but this would help make simple one-off changes easier. 

For example say I want to add to a list. With the current apis that would be
`final newList = myList.rebuild((b) => b.add(v));`
It would be nice if there was a convenience method that did the rebuild for me so i could just do:
`final newList = myList.add(v);`

**Comment by davidmorgan** [comment]
Thanks David.

I've been hesitant to add these so far; my main worries are: 1) I don't want the methods to "collide" with the mutable collections; 2) I don't know what changes might happen to the SDK in future, and it's essential that we don't collide with anything that gets added to `Iterable`; and 3) I don't want the API to encourage frequent rebuilds.

Maybe we could use e.g. `with`.

```
final newList = myList.with(v);
final newList = myList.withAll([1, 2, 3[);
final newList = myList.withRemoved(1);
```

but that doesn't address the performance problem. (In particular it'd be really bad if people start chaining these methods!)

Still, I agree it would be nice to do something here.

It's probably more of a curiosity than a solution, but note that we could create a static method called `add` that would allow you to do:

```
final newList = myList.rebuild(add(v));
```

... maybe something along those lines would work?

**Comment by pschiffmann** [comment]
+1 for not adding `add()` to `BuiltList` because it's semantically misleading. `Collection.add` is connoted with in-place modification in Dart.

My suggestion would be to implement the `+` operator that was added to List in Dart 2: [https://api.dartlang.org/dev/2.0.0-dev.69.4/dart-core/List/operator_plus.html]() This could accept both regular `List`s and `BuiltList`s.

But another question for @davidmarne: what use case do you have that requires frequent rebuilds? For example, if you only need comparability, you can use mutable lists and [package:collection](https://pub.dartlang.org/documentation/collection/latest/collection/ListEquality-class.html).

**Comment by davidmorgan** [comment]
FWIW, I do plan to add `+`, but I'd like it to be symmetrical, i.e. only accepts `BuiltList`. Having it so `a + b` works but `b + a` doesn't seems problematic to me.

**Comment by davidmarne** [comment]
@davidmorgan 
Not sure I understand 1. Why does it matter if methods collide with mutable collection methods? 

I think 2. Is definitely a valid concern, but seems a little over cautious. 

I figured 3. was gonna come up :)
IMO that is the consumers fault if they chain said methods and use the library in a imperformant manner :man_shrugging: 

However, now that I think about it I agree with @pschiffmann that it is semantically misleading. I'm thinking one of @davidmorgans alternative proposals would better solution for that reason. 

@pschiffmann 
My use case is using built_collections with redux.dart. With a pattern like redux, you don't want to use mutable lists because you want to require that the only way to update your store's state is by dispatching actions. If I used mutable comparable collections in my state object then my view code could mutate that list without dispatching an action.

**Comment by davidmorgan** [comment]
The problem with colliding with mutable collection methods is readability--if people see `list.add` they'll expect it to behave like the SDK `List.add`.

You could try adding your own top level `add` method (it can live anywhere) and using it as in my example--see how that works for you?

**Comment by davidmarne** [comment]
gotcha. That is fair, these are all good arguments, I say
