### ISSUE TITLE
UnimplementedError: Map in CopyOnWriteMap

### ISSUE THREAD

**Issue by techyrajeev** [google/built_collection.dart#157]
is there any example of using map over linkedHashMap.
I tried below code but it gives me **UnimplementedError: Map**
`vm.data.map((k,v) { return new MapEntry<String, Person>(k, new TabView(v));} )
`

data object in view model is a map with Key String and Value as Person
I referred to below documentation
https://api.dartlang.org/stable/2.0.0/dart-core/Map/map.html

**Exception:**

```
I/flutter (15116): When the exception was thrown, this was the stack:
I/flutter (15116): #0      CopyOnWriteMap.map (package:built_collection/src/internal/copy_on_write_map.dart:62:5)
```

**Comment by davidmorgan** [comment]
Sorry about that--yes, there are a bunch of things that need updating for Dart 2. I was waiting for everything to stabilize. Now that Dart 2 stable is out, it's time :) ... will get to it as soon as I can!

**Comment by techyrajeev** [comment]
If I can be of any help please let me know. I will definitely like to contribute :100: 
But will need little bit of guidance

**Comment by davidmorgan** [comment]
This was fixed.
