### ISSUE TITLE
How do I insert an entry to a built map in a built list?

### ISSUE THREAD

**Issue by rockingdice** [google/built_collection.dart#165]
I used built collection in built_redux.

I have my action defined as:

void filterUpdateData(
    AppState state, Action<FilterData> action, AppStateBuilder builder) {}

I can access the map from builder:

builder.itemList[builder.itemIndex].itemMap

But the itemMap is a builtMap, not a MapBuilder which I can insert entries.

I tried to use itemMap.toBuilder() then insert entries but with no success.

What is the correct way to do this?

**Comment by davidmorgan** [comment]
This question comes up a lot. The answer is you need to assign to the top level builder.

```
builder.itemList[builder.itemIndex] = builds.itemList[builder.itemIndex].rebuild((b) => b..<make changes here>
```

More detail here: https://github.com/google/built_collection.dart/issues/145

**Comment by rockingdice** [comment]
@davidmorgan Thanks!
