### ISSUE TITLE
Proposed additional methods for ListMultimapBuilder.

### ISSUE THREAD

**Issue by har79** [google/built_collection.dart#166]
We're using BuiltListMultimap to represent a tree structure (parent -> [children]). There are some modifications we're doing which are made harder by being unable to look up values using the Builder. For example, inserting a node at a specific location:

```
void _add(ListMultimapBuilder<Node, Node> b, Node node, Node parent, int index) {
  final oldValues = b.build()[parent];
  b
    ..removeAll(parent)
    ..addValues(parent, oldValues.rebuild((b) => b.insert(index, node)));
}
```

Similarly, replacing an existing node with a new version requires building `oldValues` to look up the index of the old node.

Adding direct support in the Builder for these mutations would be more efficient and much more convenient, specifically:

*   Changing `remove` and `removeAll` to return the value(s) removed. This would be consistent with the `ListMultimap` interface and with `BuiltList`.
*   Adding an optional `index` parameter to `add`.
*   Adding a `replace(K parent, V old, V new)` method.

Although a more flexible solution would be to have the BuiltListMultimap interface available in ListMultimapBuilder as well, but that's a much bigger change.

Thoughts? I'm happy to work on a PR if there's a good solution.

**Comment by davidmorgan** [comment]
Thanks Harry. Agreed, it makes sense to make changes in this direction--it was just for lack of time that I only made them for `BuiltList`, `BuiltMap` and `BuiltSet`.

Where possible I'd like to keep the methods equivalent to `ListMultimap` methods, but I think we're a bit less constrained there than with the SDK classes.

**Comment by har79** [comment]
Yeah, I'm keen on staying consistent `ListMultimap` as well. A more consistent suggestion:

*   Change remove and removeAll to return the value(s) removed. 
*   Add `operator [](Object key) → ListBuilder<V>`

Which would change inserting a node to be `b[parent].insert(index, node)`.

This doesn't address replacing an item, but that could then be fixed with:

*   Add `ListBuilder.replaceElement(E old, E new)`

Allowing `b[parent].replaceElement(old, new)`.

**Comment by olavemil** [comment]
One issue with how this works right now seems to be that modifications made to the returned ListBuilder can get dropped, which seems counterintuitive:
```
var builder = existingBuiltListMultimap.toBuilder();

builder[key].add(value);
var rebuilt = builder.build();
//rebuilt == builder

builder.add(key, value);
rebuilt = builder.build();
//rebuilt != builder
```
From glancing at the code this seems to be because creating the builder through `.toBuilder()` sets `_builtMapOwner`, which means any changes to `_builderMap` (such as from modifying the returned ListBuilder) are ignored during `build()`. This may be intentional, but made for some obscure bugs.

Perhaps instead of checking to see if `_builtMapOwner` has been set, `build()` should check whether `_builderMap` has any contents?

**Comment by davidmorgan** [comment]
That's a bug; thanks for reporting. I think the correct fix is to call `_makeWriteableCopy` when returning a values builder. I've filed a separate issue.

https://github.com/google/built_collection.dart/issues/183
