### ISSUE TITLE
BulitMap<BuiltType, NonBuiltType> generates <BuiltType, dynamic> in generated files

### ISSUE THREAD

**Issue by tobytraylor** [google/built_collection.dart#171]
If i use a built map where the key is a non built type the generated files use dynamic for the type.  Work around is just going through after generation and replacing them with the correct type.  

built_collection: "4.1.0"
built_value_generator: "6.3.2"
built_value: "6.3.2"

**Comment by davidmorgan** [comment]
This is a `built_value` question, not a `built_collection` question; please re-open over there if it's still a problem.
