### ISSUE TITLE
Concurrent modification during iteration: _LinkedHashMap len:0

### ISSUE THREAD

**Issue by edwardez** [google/built_collection.dart#187]
* Dart SDK Version (`dart --version`)
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (9 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
(I'm using flutter to developer a mobile app)

First, I'm not sure if this is a issue of built_collection, or dart SDK, or my code. But I feel like it's more likely a issue of built_collection so I want to report it here first.

So here is what happened: I'm randomly seeing this error in my code, both in JIT & Compiled AOT app.
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Exception: Concurrent modification during iteration: _LinkedHashMap len:0.
#0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:443:7)
#1      Iterable.firstWhere (dart:core/iterable.dart)
#2      DiscussionParser._isMutedDiscussionItem (package:munin/providers/bangumi/discussion/parser/DiscussionParser.dart:157:53)
#3      DiscussionParser.processDiscussionItems (package:munin/providers/bangumi/discussion/parser/DiscussionParser.dart:173:12)
#4      processDiscussion (package:munin/providers/bangumi/discussion/parser/isoldate.dart:15:8)
#5      _IsolateConfiguration.apply (package:flutter/src/foundation/isolates.dart:110:16)
#6      _spawn.<anonymous closure> (package:flutter/src/foundation/isolates.dart:117:45)
<asynchronous suspension>
#7      Timeline.timeSync (dart:developer/timeline.dart:161:22)
#8      _spawn (package:flutter/src/foundation/isolates.dart:115:18)
<asynchronous suspension>
#9      _startIsolate.<anonymo<…>
flutter: Another exception was thrown: Exception: Concurrent modification during iteration: _LinkedHashMap len:0.
```

[here](https://github.com/edwardez/BangumiN/blob/82552af1fa88af5d3bef6f3d1eac0c48fb94b9a9/app/lib/providers/bangumi/discussion/parser/DiscussionParser.dart#L157) is the corresponding code and [here](https://github.com/edwardez/BangumiN/blob/82552af1fa88af5d3bef6f3d1eac0c48fb94b9a9/app/lib/models/bangumi/setting/mute/MuteSetting.dart#L15) is the corresponding built_value class 

I basically pass a nested built_value class into a new isolate, and check a value in `BuiltMapA.BuiltMapB.values.firstWhere`, more specifically, I believe while I saw this error BuiltMapB is an empty `BuiltMap`.

I think it's more likely due to an issue in built_value because 
1. I don't think I'm modifying this `BuiltMap` in my code during iteration, and it happened randomly (1 time out of 100?), but once it started happenning I can steadily reproduce it until I restart the app. 
2. It always happens in the same line, same column of my code, which is related to built_value: `BuiltMapA.BuiltMapB.values.firstWhere`

Any thoughts on what might be the root cause?

**Comment by davidmorgan** [comment]
How do you pass the data between isolates?

I think it's likely a flutter/SDK issue to do with that.

**Comment by edwardez** [comment]
> How do you pass the data between isolates?
> 
> I think it's likely a flutter/SDK issue to do with that.

I simply wrap message I want to sent in a [plain dart object](https://github.com/edwardez/BangumiN/blob/ce9ab520855503c1c2db3ccf6c1adff2ebe23437/app/lib/providers/bangumi/discussion/parser/isoldate.dart#L18)([“In the special circumstances ... also possible to send object instances”](https://api.flutter.dev/flutter/dart-isolate/SendPort/send.html) then use flutter’s [compute](https://api.flutter.dev/flutter/foundation/compute.html)

Maybe I should open a new issue in Dart SDK component then?

**Comment by davidmorgan** [comment]
I suspect the problem is that sometimes when the object is being sent across the isolate, it's also being used. i.e. it gets copied while it's being iterated over.

**Comment by edwardez** [comment]
> I suspect the problem is that sometimes when the object is being sent across the isolate, it's also being used. i.e. it gets copied while it's being iterated over.

I'm passing non-nested `built_value` class in other ten-ish places but never see this error, here's the only place I'm passing a nested `BuiltMapA.BuiltMapB` and this error happens. Maybe there's something wrong in copying nested class.. Thanks for the reply. I'll contact SDK team then.

**Comment by felix-ht** [comment]
i am getting the same error - 100% reproducible in a test during. Happening with quite deeply nested built objects. The weird thing is that no concurrent code is running when this error happens. I setup the other isolates with the compute function call passing built objects as part of the params. The error only started showing up during after i added the compute function.

**Comment by Vedsaga** [comment]
Same issue, I am getting here too.... @edwardez is it resolved it for you ? if so pls could you share...

**Comment by Vedsaga** [comment]
> i am getting the same error - 100% reproducible in a test during. Happening with quite deeply nested built objects. The weird thing is that no concurrent code is running when this error happens. I setup the other isolates with the compute function call passing built objects as part of the params. The error only started showing up during after i added the compute function.

@felix-ht is it resolved it for you ?

**Comment by felix-ht** [comment]
@Vedsaga  No I removed the compute function causing the issue and decided to life with the jank for now ...

**Comment by felix-ht** [comment]
Thinking about this in retrospective - it's not unexpected that the compute is done as this happens. As there is no memory sharing between isolates. Issues can only happen before or after it finishes.

Might try to come up with a minimal example to that reproduces this behavior.

**Comment by Vedsaga** [comment]
> Might try to come up with a minimal example to that reproduces this behavior.

I also avoid looping over ever changing loop and instead of that, I now use function which returns bool that check if elements exist or not... 

This approach solve the problem for me
