### ISSUE TITLE
typesafe contains

### ISSUE THREAD

**Issue by frickt** [google/built_collection.dart#191]
Could we change
`bool contains(Object element)`
to
`bool contains(covariant E element)`
in all collections to have a typesafe contains function, or is there a reason to have Object there?

To not break code may be introduce a new containsChecked(E element) or so?

**Comment by davidmorgan** [comment]
The API here is based on the SDK; it's nice to have it match exactly.

We could maybe introduce a lint for when the type doesn't match, like https://dart-lang.github.io/linter/lints/iterable_contains_unrelated_type.html

**Comment by frickt** [comment]
ok, understand, thank you for the lint link!
