### ISSUE TITLE
toJson not implemented on built_collection collections

### ISSUE THREAD

**Issue by dave-doty** [google/built_collection.dart#195]
I'm sorry, I'm not quite sure who is "responsible" for this, so it may not be this library, but some combination of built_collection, over_react, and redux.dart is not working for me.

I'm using [over_react](https://pub.dev/packages/over_react) and [redux.dart](https://pub.dev/packages/redux), and my redux state is a built_value tree composed of other built_value objects recursively, as well as many built_collection collections such as `BuiltList`.

The following warning occurs with `DevToolsStore` (provided by redux.dart, but used in combination with OverReactReduxDevToolsMiddleware from the dart [over_react package](https://pub.dev/packages/over_react)):

*OverReactReduxDevToolsMiddleware [WARNING]: You must implement a `toJson` method in your state and actions in order to view state changes in the redux dev tools.*

It's a bit generic, but I tracked down the source of the error. It is because I am using built_collection in my state, and those classes do not implement `toJson`.

Here's a self-contained example:

```dart
var state = BuiltList<int>([2, 5]);
store = DevToolsStore<BuiltList<int>>((s, _) => s, initialState: state, middleware: [overReactReduxDevToolsMiddleware]);
```

I tried adding the following code to enable `BuiltList` to have a `toJson` method, but I still get the warning, and ReduxDevTools is not able to display the state in the Chrome plugin.

```dart
extension BuiltListSerializable<E> on BuiltList<E> {
  dynamic toJson() => this.toList();
}
```

The error does not occur with built_value objects, because I define those myself (unlike `BuiltList`, `BuiltMap`, `BuiltSet`) and can add a `toJson` method to them. To do this I define a mixin as follows:

```dart
@SerializersFor([
  // big list of all my built_value classes
])
Serializers serializers = _$serializers;
Serializers standard_serializers = (serializers.toBuilder()..addPlugin(new StandardJsonPlugin())).build();

mixin BuiltJsonSerializable {
  dynamic toJson() => standard_serializers.serialize(this);
}
```

**Comment by davidmorgan** [comment]
Hmm, that sounds to me like an issue for `over_react`; either to get the extension method to work (I guess, there is an import missing somewhere) or to allow you to plug in a different way of serializing.

**Comment by dave-doty** [comment]
I figured this out: https://github.com/Workiva/over_react/issues/424#issuecomment-559228858
