### ISSUE TITLE
add extension method toBuilder() for dart collections

### ISSUE THREAD

**Issue by dave-doty** [google/built_collection.dart#196]
Using Dart 2.6 extension methods, a `build()` method was added to collections such as `List`, so that one can type

```dart
BuiltList<int> build_list = [2,3,5,7,11].build();
```

It would be great also to have a method `toBuilder()` that returns an instance of `ListBuilder`.

Currently, the syntax is still awkward for nested builders in a `Built` instance. For example, if I create a class `MyValue` implementing `Built` with a field `nums` of type `BuiltList<int>`, then I it would be great to be able to do the following:

```dart
MyValueBuilder value_builder = MyValueBuilder();
...
value_builder.nums = [2,3,5,7,11].toBuilder();
...
MyValue value = value_builder.build();
```

Currently, the workaround is the more awkward, less "chainable"

```dart
value_builder.nums = ListBuilder<int>([2,3,5,7,11]);
```

or the more verbose and less efficient

```dart
value_builder.nums = [2,3,5,7,11].build().toBuilder();
```

**Comment by davidmorgan** [comment]
For nested collections the intended usage is

```
nums.replace([2, 3, 5, 7, 11])
```

--generally you shouldn't need to use builders explicitly.

This falls down when you have 2D or higher collections, e.g. `BuiltList<BuiltList<int>>`. I'm exploring using extension methods to improve how these work :)
