### ISSUE TITLE
allow construction of nested built collections from nested mutable collections

### ISSUE THREAD

**Issue by dave-doty** [google/built_collection.dart#198]
The following would be nice to have:

```dart
List<List<int>> list = [[1, 2], [3, 4]];
BuiltList<BuiltList<int>> built_list = list.build();
```

and similarly for constructing `BuiltMap<String, BuiltList<int>>` from `Map<String, List<int>>`, etc.

Unfortunately it causes this error: `Error: Expected a value of type 'BuiltList<int>', but got one of type 'List<int>'`

The workaround is to reach in to the nested collection and do the conversion manually:

```dart
List<List<int>> list = [[1, 2], [3, 4]];
List<BuiltList<int>> partially_built_list = [for (var sublist in list) sublist.build()];
BuiltList<BuiltList<int>> built_list = partially_built_list.build();
```

But this isn't concise, and would get worse with more nesting.

Is there a more concise way to say "convert this hierarchy of collections to a hierarchy of built collections?

**Comment by davidmorgan** [comment]
You can also do it like this:

```
var builtList = [
    [1, 2].build(),
    [3, 4].build()].build();
```

We could add more extension methods so you don't need the inner `build`, but I'm not sure it's worth it.
