### ISSUE TITLE
Travis: enable weekly cron job

### ISSUE THREAD

**Issue by kevmoo** [google/built_collection.dart#203]
Under settings: https://travis-ci.org/google/built_collection.dart

This ensures we get "fresh" runs against the most recent Dart dev SDKs – a good way to catch regressions before we get to stable!

**Comment by kevmoo** [comment]
@davidmorgan – please? 🙏

**Comment by davidmorgan** [comment]
Thanks for pinging.

I don't see a 'settings' tab. It looks like I can go directly to it here:

https://travis-ci.org/google/built_collection.dart/settings

But changes I make don't appear to be saved--the row in the table representing the new cron appears briefly then disappears.

Any ideas please?

**Comment by kevmoo** [comment]
Can you give me rights to the repo? Let me see if I can do it

**Comment by davidmorgan** [comment]
Sure, you're invited/added. Thanks.

**Comment by kevmoo** [comment]
The drop-down is weird. You have to type in master. Fixed it!

**Comment by davidmorgan** [comment]
Weird indeed--that's what I did, didn't work. I see the one you added; still doesn't work if I try to add a 'monthly' run in addition. Anyway, seems we're good now. Thanks :)
