### ISSUE TITLE
[FR] make safeList public, or BuiltList(_safeList), or whatever.

### ISSUE THREAD

**Issue by lukepighetti** [google/built_collection.dart#205]
```dart
  /// As [List.retainWhere].
  ///
  /// This method is an alias of [where].
  void retainWhere(bool Function(E) test) {
    _safeList.retainWhere(test);
  }
```

It appears that we don't have any way to add extension methods to `ListBuilder` to add methods like `void toggle(T e)` because we cannot access the list that `ListBuilder` is working with. It seems reasonable to have access to the BuiltList in ListBuilder as a public member so we can make our own extension methods that operate from the underlying data.

**Comment by davidmorgan** [comment]
Unfortunately if we allow access to `_safeList` it is no longer safe :) ... it would be possible to break the guarantees of `BuiltList`, making it no longer immutable, by leaking references to `_safeList`.

**Comment by lukepighetti** [comment]
Reasonable. Thanks.
