### ISSUE TITLE
BuiltList has no setter for length

### ISSUE THREAD

**Issue by ttencate** [google/built_collection.dart#213]
Dart's `List` class supports setting `length`, which trims the list if it's too long, and adds `null`s if it's too short. `ListBuilder` does not support this. It seems trivial to add, and would be nice for consistency.

Use cases:

```dart
// Trim to a maximum size.
if (builder.length > maxLength) builder.length = maxLength;
// Workaround, longer and less readable.
if (builder.length > maxLength) builder.removeRange(maxLength, builder.length);

// Reserve elements to prevent needless allocations. Rare but conceivable.
builder.length = reservedLength;
for (var i = 0; i < reservedLength; i++) builder[i] = ...;
```

**Comment by davidmorgan** [comment]
builders aren't allowed to contain nulls, currently, so I'm afraid it's nontrivial :)

**Comment by ttencate** [comment]
Ahhh, I overlooked that :) I needed it only for shortening, which is easily implemented, but you'd have to assert-fail when trying to lengthen the builder, which is not the greatest API. Of course, feel free to close this if it can't be sensibly implemented!
