### ISSUE TITLE
Serialize BuiltListMultimap

### ISSUE THREAD

**Issue by mzafer** [google/built_collection.dart#214]
The StandardJsonPlugin does not support serialization of BuiltListMultimap, how to serialize BuiltListMultimap<String, BuiltType> ?

Thanks
Zafer

**Comment by davidmorgan** [comment]
I'm afraid it's not supported; you'll need to either not use `StandardJsonPlugin`, or not use `BuiltListMultimap`.

I don't remember why it's not supported; I suppose it doesn't map well onto JSON for some reason. Sorry about that.

**Comment by mzafer** [comment]
Ooh, deserialization is supported though. Anyway thanks for the reply, I'll look for an alternative.

**Comment by davidmorgan** [comment]
This is a `built_value` question, please re-open in the `built_value` repo if it's still an issue. Thanks.
