### ISSUE TITLE
BuiltList serialization seems to require specifiedType 

### ISSUE THREAD

**Issue by felix-ht** [google/built_collection.dart#221]
So i have a class called Company setup with BuiltValue and serializer. 
Company gets wrapped in a BuiltList.

Now the issue is that whenever i want serialize the list i have to supply a specifiedType or the serialization fails caused by a type check.

 ```dart
/// to the serializer builder i added:
         ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Company)]),
          () => new ListBuilder<Company>())

  test('Test pass through BuiltList Company', () async {
    var companyA = Company((b) => b
      ..objectId = "A"
      ..name = "A");
    var companyB = Company((b) => b
      ..objectId = "B"
      ..name = "B");

    BuiltList<Company> list = BuiltList<Company>([companyA, companyB]);
    var json = serializers.serialize(list,
        specifiedType:
            const FullType(BuiltList, const [const FullType(Company)]));

    BuiltList<Company> listAfter = serializers.deserialize(json,
        specifiedType:
            const FullType(BuiltList, const [const FullType(Company)]));
    expect(list, equals(listAfter));

    list = BuiltList<Company>([companyA, companyB]);
    json = serializers.serialize(list);

    var listAfterNonStatic = serializers.deserialize(json);
    expect(list, equals(listAfterNonStatic));

    listAfter = listAfterNonStatic;  // line 61 <- fails here
    expect(list, equals(listAfter));
  });
```
This fails with:
``` bash
flutter test
00:01 +1 -1: Test pass through BuiltList Company [E]
type '_BuiltList<Object>' is not a subtype of type 'BuiltList<Company>'
built_value_models_test.dart 61:5  main.<fn>
  
00:01 +2 -1: Some tests failed. 
```
So serialize/deserialize actually creates the proper objects but casting to the static type fails.

Do i always have to pass specifiedType or is there another option?
It would be very useful if serializers.serialize would work with any type to built object I pass in.

(I know that if if a built object holds the BuiltMap built_runner generates the code so that there is no need to pass specifiedType but this is not always desirable)

**Comment by davidmorgan** [comment]
Not really, sorry; the only way to get a list of the complete type, `BuiltList<Company>` is with `specifiedType`.

Otherwise you'll get a `BuiltList<Object>`. You could turn that into a `BuiltList<Company>` with e.g. `BuiltList<Company>.from(serializers.deserialize(json) as BuiltList)` but that's not much better. (Slower at runtime since it's another copy).

**Comment by felix-ht** [comment]
Thanks! Just wanted to make sure that i am not missing something stupid. Is there any potential to add support for this in the library or is this a fundamental dart constraint?

**Comment by davidmorgan** [comment]
I can't see a better way of doing it; the code creating the list has to know what type of list it should be.

We could write the type in the JSON, e.g. `list<int>` as a string, but there are lots of nasty corners around implementing that, I don't think it would be worth it.
