### ISSUE TITLE
Copy on write collections are missing generics in return types

### ISSUE THREAD

**Issue by davidmorgan** [google/built_collection.dart#26]
e.g. CopyOnWriteList.takeWhile returns Iterable instead of Iterable<E>.

**Comment by BlackHC** [comment]
Huh?

**Comment by davidmorgan** [comment]
Erm. I mean "Iterable instead of Iterable<E>".

**Comment by BlackHC** [comment]
Ah angular brackets are stripped out, you might want to embed the code bits
in ticks maybe ^^

**Comment by davidmorgan** [comment]
Heh. Okay, third try:

`Iterable instead of Iterable<E>`

**Comment by davidmorgan** [comment]
Fixed.
