### ISSUE TITLE
Add BuiltMultiset

### ISSUE THREAD

**Issue by davidmorgan** [google/built_collection.dart#27]

**Comment by matanlurey** [comment]
This is closable, yeah :) @davidmorgan

**Comment by davidmorgan** [comment]
Eh? I never got around to adding multiset (as opposed to multimap) ... did you mean another issue? :)

**Comment by davidmorgan** [comment]
There haven't been any more requests for this. Closing for now.

**Comment by alanrussian** [comment]
I ran into a situation where I could use this today. Please consider keeping it open. I think it would be useful.

**Comment by davidmorgan** [comment]
Thanks Alan. To be honest--I think nearly two years between requests makes it pretty low priority. But we can keep the issue open :)
