### ISSUE TITLE
Add support for returning typed collections in Strong mode

### ISSUE THREAD

**Issue by har79** [google/built_collection.dart#53]
Using map on a built collection in strong mode produces a warning. For example,
    BuiltSet<int> is = new BuiltSet(const [1, 2, 3]);
    Iterable<String> ss = is.map((i) => '$i');
produces
    Unsound implicit cast from Iterable<dynamic> to Iterable<String>

This can be fixed by changing BuiltSet.map from
    Iterable map(f(E element)) => _set.map(f);
to
    Iterable/*<T>*/ map/*<T>*/(/*=T*/ f(E e)) => _set.map(f);
as in the built-in Iterable: https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/iterable.dart#L159

I'm working on a patch to fix this across built_collection.

-- hcameron@

**Comment by davidmorgan** [comment]
Great, thanks.

Another change we'll be looking at for strong mode is getting rid of any runtime checks that can be caught by strong mode warnings. That will be a major version bump, though, since people will have to understand what's changed and what happens if they're _not_ strong mode clean.
