### ISSUE TITLE
Copy constructor returns wrong type

### ISSUE THREAD

**Issue by dskloetg** [google/built_collection.dart#56]
B extends A

```
listB = new BuiltList<B>();
listA = new BuiltList<A>(listB);
```

In this case listA has the same runtime type as listB because `listA is BuiltList<B>` evaluates to true in the copy constructor of BuiltList. This later causes problems when trying to rebuild listA with new elements of type A.

**Comment by dskloetg** [comment]
See also https://dartpad.dartlang.org/aa9be31bd7746fd94728

`<B>[] is List<A>` evaluates to true which seems wrong.

**Comment by davidmorgan** [comment]
Thanks!

We should probably switch to using just .runtimeType == ... and add some tests.
