### ISSUE TITLE
new BuiltList<A>(builtListOfB) should be efficient

### ISSUE THREAD

**Issue by dskloetg** [google/built_collection.dart#66]
B extends A.
If we have a `BuiltList<B>` but we need it as a `BuiltList<A>`, we currently need to create a copy of the list.
new `BuiltList<A>()` should be able to reuse the underlying list and without checking the type of each element.

**Comment by davidmorgan** [comment]
Now that we get rid of explicit type checks and just rely on the checks of the underlying collection, I think this is unfortunately infeasible.
