### ISSUE TITLE
Documentation on iteration order

### ISSUE THREAD

**Issue by PowerSander** [google/built_collection.dart#67]
The documentation of the BuiltSet states that "It preserves iteration order."

It wasn't clear to me that this means/implies that the iteration order is the insertion order. Could this be made clearer in the documentation?

**Comment by davidmorgan** [comment]
Thanks! How's this:

https://github.com/google/built_collection.dart/pull/68

?

**Comment by davidmorgan** [comment]
Merged. Thanks.
