### ISSUE TITLE
Get value from MapBuilder

### ISSUE THREAD

**Issue by jonaskello** [google/built_collection.dart#7]
It seems like MapBuilder only supports setting values, not getting them. My scenario is that I am using a ```MapBuilder<String, List<Foo>>```. I have a loop where for each iteration the List<Foo> for a particular String key in the map may be added to for a particular key in the map. I tried something like this but it does not seem to work since I cannot fetch the value for the key.

```dart
   var builder = new MapBuilder<String, List<Foo>>();
   for (Bar bar in bars) {
      var list = builder[bar.name]; // This line fails
      if(list == null) {
       list = new List<Foo>();
       builder[bar.name] = list;
      }
      list.add(bar.foos);
    }
```

Is there some other way to solve this scenario? I could use a regular Map in the loop and then create the MapBuilder from that, but I feel that would defeat the purpose of a MapBuilder :-).

**Comment by davidmorgan** [comment]
Have you seen ListMultimap, from quiver?

https://github.com/google/quiver-dart/blob/master/lib/src/collection/multimap.dart

The plan is to have a Built version of it at some point. I think that would be a perfect fit for what you're doing?

**Comment by jonaskello** [comment]
Yes that looks useful. I guess from the outside ```ListMultiMap<String, Foo>``` is pretty much the same as ```Map<String, List<Foo>>``` but the internals are different?

**Comment by davidmorgan** [comment]
It has a few additional useful methods on the interface, and, crucially, it handles creating empty lists for you. So once we have ListMultimapBuilder your code should simplify to:

var builder = new ListMultimapBuilder<String, Foo>();
for (Bar bar in bars) {
  builder.add(bar.name, bar.foos);
}

**Comment by davidmorgan** [comment]
Here is the pull request for BuiltListMultimap if you want to take a look before it goes in:

https://github.com/google/built_collection.dart/pull/8

It'll be in some time next week, most likely.

**Comment by davidmorgan** [comment]
Now published to pub. Please let us know if it works for you :)

**Comment by jonaskello** [comment]
Thanks for adding this! I ended up doing it in another way in the meantime. But I'm sure it will come in handy soon again. I'll let you know if I find any bugs when I use it :-).
