### ISSUE TITLE
Add BuiltIterable for return values of Iterable

### ISSUE THREAD

**Issue by davidmorgan** [google/built_collection.dart#82]
By wrapping in a new class we can provide extra utility methods, e.g. toBuiltList, toBuiltSet.

This will be helpful for the "map" method on built collections, to allow you to map then convert immediately into another built collection.

**Comment by davidmorgan** [comment]
This actually doesn't work right now, except with DDC. The problem is that although generic methods can enforce the type of the returned iterable for "map" statically, the type is dropped at runtime. Will need to wait for Dart improvements.

**Comment by lohnicky** [comment]
BuiltIterable would be also useful for the input interfaces in the angular components. This way we could force the component users to pass immutable values via the interface which would prevents them to pass normal lists, changing them and expecting that the change will be reflected in the component.

**Comment by davidmorgan** [comment]
I think this is obsoleted by extension methods.
