### ISSUE TITLE
BuiltMap<String, BuiltSet<String>> updates

### ISSUE THREAD

**Issue by BlackHC** [google/built_collection.dart#91]
How do I add an element to a contained BuiltSet?

MapBuilder does not allow me to retrieve elements and update them. Why is there no operator []?

Ideally, there was special casing for keys and values of BuiltMap such that toBuilder returned MapBuilder<String, ListBuilder<String>> in this case.

---

What's a good workaround?

Right now, I've only been able to come up with:
```dart
BuiltMap<String, BuiltSet<String>> setMap;
String key, value;

setMap = setMap.rebuild((b) => 
    b[key] = (setMap[key] ?? new BuiltSet<String>()).rebuild((b) => b.add(value)));
```

---

Thanks,
 Andreas

**Comment by davidmorgan** [comment]
Ignoring the general problem -- shouldn't you be using a BuiltSetMultimap here?

**Comment by BlackHC** [comment]
Oh haha, yes, of course :D I feel like I might have contributed to the original implementation.

Not sure what to do about the operator [] though. I have run into this a couple more times. Usually I just end up setting the builder but access the built object. This is not optimal because I need to build it on every iteration to avoid staleness..

Maybe I should just use List etc within algorithms that calculate things. Somehow I like to stay within the Built* API though.

**Comment by davidmorgan** [comment]
Yeah, it probably does make sense to add [].

**Comment by davidmorgan** [comment]
I've also looked at special built collections that know they contain buildable values -- I think it's workable, but needing a new class name and needing more generics is a bit horrible. Also you need to supply a builder factory:

```
var listOfLists = new NestedBuiltList<BuiltList<int>, ListBuilder<int>>(() => new ListBuilder<int>());
listOfLists.buildAndAdd((b) => b..add(1));
listOfLists.rebuildAt(0, (b) => b..add(2));
```

Not sure it's worth it.

**Comment by ranquild** [comment]
Actually built list of built value classes is very common case. I would like to have that bridge between those two libraries.

**Comment by davidmorgan** [comment]
Yes, I've been trying to think of a way to do that https://github.com/google/built_collection.dart/issues/83
