### ISSUE TITLE
Add getters to builders

### ISSUE THREAD

**Issue by davidmorgan** [google/built_collection.dart#92]
Sometimes you do need getters to be able to do inline updates.

The same getters as List/Map/Set/etc should be provided, but without implementing List/Map/Set/Iterable, to prevent builders accidentally being used in place of mutable collections.

**Comment by ranquild** [comment]
+1 for this. I use built collections and I often need such functionality.

**Comment by davidmorgan** [comment]
I've added the two most important getters: List[] and Map[]. Available in 1.4.0.

Please reopen if there are others you'd like to see.
